### ISSUE TITLE
dlib 19.0

### ISSUE THREAD

**Issue by svenadlung** [menpo/conda-dlib#11]
Howdy! 
Is there any plan on updating to the new dlib v19.0? It has some major improvements and manual compiling for me always fails on my Mac since there are some conflicts with the X11 libraries. 
The conda recipe helped me out before and it would be great if you would find any chance to update :)
Thanks in advance.

**Comment by patricksnape** [comment]
There are no improvements to the Python API in 19.0. There are a bunch of improvements with respect to the new 'deep learning' API, but I am extremely unlikely to build those as I doubt I can get CUDA etc working on Travis et al.

Having said that - I've been working on getting it working over on [conda-forge](https://github.com/conda-forge/staged-recipes/pull/1177) where we were having issues with the latest version of CMake and now linking errors on Python 3.4.

I also don't compile with the GUI due to the lack of a reasonable X11 version being shipped on OSX for example.
